### PR TITLE
fix(bootstraptour):removed isJustPathHashDifferent this was causing r…

### PR DESCRIPTION
**Pull request by akonsowski**
…edirection errors

### CODE REVIEW

**Comment by InfamousVague** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Can you fix this in the source and then build to make the changes in the build directory instead of updating file in /build by themselves?

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Please note that this will require an associated change in ozp-center/npm-shrinkwrap.json

**Pull request merged**
